### ISSUE TITLE
2021-09-30

### ISSUE THREAD

**Issue by leewei05** [leewei05/notes#4]
Database
- We don't want DBMS always to fetch data from disk because its slow and not efficient, so we will need a `buffer pool` to manage a in-memory cache for data pages, these data pages are called `frame` in buffer pool. 
- Meta-data that are managed by `buffer pool`
  -  `Page table`: hash table for data page, it maps the page-id to the frame location
  - `Dirty flag`: set this when buffer pool modifies a page
  - `Pin Counter`: number of threads that are currently accessing the page

Kubernetes
- A `PriorityClass` is a non-namespaced object, it is shared across the entire cluster. The higher the number, the higher the priority. The scheduler will try to schedule Pod with higher priority in the queue.

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: high-priority
```

Others
- `Twirp`: a rpc framework supports HTTP1.1. It will handle routing, serialization, HTTP methods and we can focus on the implementation of our business logic code.
- `Serialization`: the process of converting an object into a stream of bytes
